### ISSUE TITLE
node-cryptonode-pool show incorrect header check.

### ISSUE THREAD

**Issue by p2svn9x** [felixbrucker/miner-monitor#3]
[2018-05-23 04:15:57] [Pool :: Node-Cryptonote-Pool-API] => incorrect header check

thanks

**Comment by felixbrucker** [comment]
which pool url did you enter in the config?

**Comment by p2svn9x** [comment]
my solo pool at http://etn-mine.com:8117

**Comment by felixbrucker** [comment]
i can't connect to it so i can't test anything

**Comment by p2svn9x** [comment]
thanks for your responding
you can check website at http://p2s.vn
however pool api at http://etn-mine.com:8117
i can check by hand at http://etn-mine.com:8117/stats

**Comment by felixbrucker** [comment]
![image](https://user-images.githubusercontent.com/5189997/40391778-c17c22de-5e19-11e8-85a5-db46022d441e.png)

it seems your api is not reachable

**Comment by p2svn9x** [comment]
![77218174-9f1d-4bed-8a47-f59ba433662a](https://user-images.githubusercontent.com/37497642/40392167-de9554c8-5e44-11e8-93f4-83ceff193bdf.jpeg)


hmm. i think nothing wrong with my api.
i tried with other pool url and got same error
http://etn.kkmining.club

**Comment by felixbrucker** [comment]
Using this url worked, however i see the same error on my side

i verified it isn't solved by upgrading nodejs, axios or using another request library. As such the issue seems to lie in some change made to the pool software/api. Which repo did you use to setup your own pool (where it does show the same error)?
